name: Build and deploy

on:
  push:
    branches:
    - main

env:
  CONFIGURATION: Release
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Create client appsettings.json
      run: 'echo "$CLIENT_APPSETTINGS_JSON" > Blace.Client/wwwroot/appsettings.json'
      shell: bash
      env:
        CLIENT_APPSETTINGS_JSON: ${{ secrets.CLIENT_APPSETTINGS_JSON }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Install workload
      run: dotnet workload install wasm-tools

    - name: Restore packages
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish

    - name: Deploy Server
      uses: azure/webapps-deploy@v2
      with:
        app-name: blace-server
        publish-profile: ${{ secrets.SERVER_PUBLISH_PROFILE }}
        package: Blace.Server/bin/Release/net8.0/publish

    - name: Deploy Client
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.CLIENT_DEPLOYMENT_TOKEN }}
        action: upload
        skip_app_build: true
        app_location: Blace.Client/bin/Release/net8.0/publish/wwwroot
        output_location: ''